name: CI
on: [push, pull_request]
defaults:
  run:
    shell: pwsh
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test with Pester
        run: |
          Install-Module -Name Pester -Force -SkipPublisherCheck -MinimumVersion '5.0'
          Import-Module Pester -MinimumVersion '5.0'
          Invoke-Pester -CI
      - name: Invoke action
        run: |
          $env:INPUT_SCRIPT = 'Write-Host "ok"; return "value"'
          $output = node ./dist/index.js
          if ($LASTEXITCODE -ne 0) {
            $output | Write-Error
            throw 'node failed'
          }
          $diff = Compare-Object @('ok','::set-output name=result::value') $output -CaseSensitive
          if ($diff) {
            $diff | Format-Table | Write-Host
            throw 'Output differed from the expected'
          }
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build module docs
        run: |
          ./build-docs.ps1 -Clean
          if (git status --porcelain) {
            Write-Host "::error::Documentation isn't up to date"
            return 1
          }
  self-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get-ActionInput tests
        uses: ./
        with:
          custom-input: 'test'
          script: |
            if ((Get-ActionInput script) -notlike 'if ((Get-ActionInput script)*') {
              throw "Get-ActionInput for 'script' failed"
            }
            if ((Get-ActionInput custom-input) -cne 'test') {
              throw "Get-ActionInput for 'custom-input' failed"
            }
      - name: Set-ActionOutput test (act)
        uses: ./
        id: Set-ActionOutput
        with:
          script: Set-ActionOutput test-output 'test-value'
      - name: Set-ActionOutput test (assert)
        uses: ./
        with:
          script: |
            if ('${{ steps.Set-ActionOutput.outputs.test-output }}' -cne 'test-value') {
              throw "Set-ActionOutput failed"
            }