name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Invoke action
        shell: pwsh
        run: |
          $env:INPUT_SCRIPT = 'echo "ok"; return "value"'
          $output = node ./dist/index.js
          if ($LASTEXITCODE -ne 0) {
            $output | Write-Error
            throw 'node failed'
          }
          $diff = Compare-Object @('ok','::set-output name=result::value') $output -CaseSensitive
          if ($diff) {
            Write-Host $diff
            throw 'Output differed from the expected'
          }